### ISSUE TITLE
 Error handling request: undefined method `>=' for nil:NilClass

### ISSUE THREAD

**Issue by TeuF** [starling/starling#2]
Hi,

I install starling yesterday for the first time :) and was very happy with it.
This morning I get this little error when Iaunch $ ./script/workling_client start -t

Is it a bug ? from workling, starling ? or just my mistake :S 

Starling log:

$ starling -P tmp/pids/starling.pid -v -q log/
Starting at 127.0.0.1:22122.
I, [2009-12-27T10:39:17.121482 #31758]  INFO -- : Starling STARTUP on 127.0.0.1:22122
E, [2009-12-27T10:39:21.522923 #31758] ERROR -- : Error handling request: undefined method `>=' for nil:NilClass.
D, [2009-12-27T10:39:21.523004 #31758] DEBUG -- : /Users/teuf/.gem/ruby/1.8/gems/starling-starling-0.10.0/lib/starling/handler.rb:186:in`get'
/Users/teuf/.gem/ruby/1.8/gems/starling-starling-0.10.0/lib/starling/handler.rb:122:in `process'
/Users/teuf/.gem/ruby/1.8/gems/starling-starling-0.10.0/lib/starling/handler.rb:98:in`receive_data'
/Users/teuf/.gem/ruby/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
/Users/teuf/.gem/ruby/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run'
/Users/teuf/.gem/ruby/1.8/gems/starling-starling-0.10.0/lib/starling/server.rb:97:in `run'
/Users/teuf/.gem/ruby/1.8/gems/starling-starling-0.10.0/lib/starling/server_runner.rb:179:in`start'
/Users/teuf/.gem/ruby/1.8/gems/starling-starling-0.10.0/lib/starling/server_runner.rb:36:in `initialize'
/Users/teuf/.gem/ruby/1.8/gems/starling-starling-0.10.0/lib/starling/server_runner.rb:15:in`new'
/Users/teuf/.gem/ruby/1.8/gems/starling-starling-0.10.0/lib/starling/server_runner.rb:15:in `run'
/Users/teuf/.gem/ruby/1.8/gems/starling-starling-0.10.0/bin/starling:5
/Users/teuf/.gem/ruby/1.8/bin/starling:19:in`load'
/Users/teuf/.gem/ruby/1.8/bin/starling:19

Thanks,

**Comment by andreimaxim** [comment]
Could you please add some steps to replicate the bug?
