### ISSUE TITLE
TypeError: can't dup NilClass

### ISSUE THREAD

**Issue by slayer** [starling/starling#3]
Run starling server

```
# starling
Starting at 127.0.0.1:22122.
I, [2010-01-11T17:23:52.908535 #31822]  INFO -- : Starling STARTUP on 127.0.0.1:22122
```

Run starling client as described in Quick Start Usage

```
>> require 'starling'
=> ["Starling"]
>>  starling = Starling.new('127.0.0.1:22122')
=> MemCache: 1 servers, ns: nil, ro: false
>> starling.set('my_queue', 12345)
TypeError: can't dup NilClass
        from /opt/ruby-ee-1.8.7-2009.10/lib/ruby/gems/1.8/gems/starling-0.9.8/lib/starling.rb:94:in `dup'
        from /opt/ruby-ee-1.8.7-2009.10/lib/ruby/gems/1.8/gems/starling-0.9.8/lib/starling.rb:94:in `get_server_for_key'
        from /opt/ruby-ee-1.8.7-2009.10/lib/ruby/gems/1.8/gems/memcache-client-1.7.7/lib/memcache.rb:912:in `request_setup'
        from /opt/ruby-ee-1.8.7-2009.10/lib/ruby/gems/1.8/gems/memcache-client-1.7.7/lib/memcache.rb:877:in `with_server'
        from /opt/ruby-ee-1.8.7-2009.10/lib/ruby/gems/1.8/gems/memcache-client-1.7.7/lib/memcache.rb:361:in `set'
        from /opt/ruby-ee-1.8.7-2009.10/lib/ruby/gems/1.8/gems/starling-0.9.8/lib/starling.rb:34:in `set'
        from (irb):3
```

**Comment by andreimaxim** [comment]
You're using an older version of Starling. Please install the gem manually from the Github repository.

**Comment by slayer** [comment]
thanks
