### ISSUE TITLE
IO Timeout Errors

### ISSUE THREAD

**Issue by dharmarth** [starling/starling#4]
For a largish queue, the first few calls (set/get/fetch) fail, immediately after starling is started. I could see this issue with a queue size of ~11MB. I have uploaded the queue and test script files here: 

http://www.mediafire.com/file/mwmtu1dymrf/pid_queue.tar.gz
http://gist.github.com/298988

Error when 'fetch' method is called:

<pre><code>
[memcache-client] Could not load SystemTimer gem, falling back to Ruby's slower/unsafe timeout library: no such file to load -- system_timer
I, [2010-02-08T19:48:04.038157 #31036]  INFO -- : memcache-client 1.7.8 ["127.0.0.1:22122"]
D, [2010-02-08T19:48:04.038409 #31036] DEBUG -- : Servers now: [<MemCache::Server: 127.0.0.1:22122 [1] (NOT CONNECTED)>]
D, [2010-02-08T19:48:04.039342 #31036] DEBUG -- : get pid_queue from <MemCache::Server: 127.0.0.1:22122 [1] (CONNECTED)>
W, [2010-02-08T19:48:04.540255 #31036]  WARN -- : Socket failure: IO timeout
I, [2010-02-08T19:48:04.540566 #31036]  INFO -- : 127.0.0.1:22122 DEAD (Timeout::Error: IO timeout), will retry at Mon Feb 08 19:48:34 +0530 2010
IO timeout
/var/lib/gems/1.8/gems/memcache-client-1.7.8/lib/memcache.rb:1134:in `rbuf_fill'
/usr/lib/ruby/1.8/net/protocol.rb:116:in`readuntil'
/var/lib/gems/1.8/gems/memcache-client-1.7.8/lib/memcache.rb:1145:in `gets'
/var/lib/gems/1.8/gems/memcache-client-1.7.8/lib/memcache.rb:742:in`cache_get'
/var/lib/gems/1.8/gems/memcache-client-1.7.8/lib/memcache.rb:865:in `call'
/var/lib/gems/1.8/gems/memcache-client-1.7.8/lib/memcache.rb:865:in`with_socket_management'
/var/lib/gems/1.8/gems/memcache-client-1.7.8/lib/memcache.rb:740:in `cache_get'
/var/lib/gems/1.8/gems/memcache-client-1.7.8/lib/memcache.rb:254:in`_original_get'
/var/lib/gems/1.8/gems/memcache-client-1.7.8/lib/memcache.rb:886:in `with_server'
/var/lib/gems/1.8/gems/memcache-client-1.7.8/lib/memcache.rb:252:in`_original_get'
/var/lib/gems/1.8/gems/starling-0.10.1/lib/starling.rb:24:in `fetch' 
starling_test.rb:18
</pre></code>

Error when 'set' method is called:

<pre><code>
[memcache-client] Could not load SystemTimer gem, falling back to Ruby's slower/unsafe timeout library: no such file to load -- system_timer
I, [2010-02-08T19:50:26.896756 #31231]  INFO -- : memcache-client 1.7.8 ["127.0.0.1:22122"]
D, [2010-02-08T19:50:26.897016 #31231] DEBUG -- : Servers now: [<MemCache::Server: 127.0.0.1:22122 [1] (NOT CONNECTED)>]
D, [2010-02-08T19:50:26.898433 #31231] DEBUG -- : set pid_queue to <MemCache::Server: 127.0.0.1:22122 [1] (CONNECTED)>: 12
W, [2010-02-08T19:50:27.410790 #31231]  WARN -- : Socket failure: IO timeout
I, [2010-02-08T19:50:27.411135 #31231]  INFO -- : 127.0.0.1:22122 DEAD (Timeout::Error: IO timeout), will retry at Mon Feb 08 19:50:57 +0530 2010
No servers available (all dead)
/var/lib/gems/1.8/gems/starling-0.10.1/lib/starling.rb:138:in `get_server_for_key'
/var/lib/gems/1.8/gems/memcache-client-1.7.8/lib/memcache.rb:920:in`request_setup'
/var/lib/gems/1.8/gems/memcache-client-1.7.8/lib/memcache.rb:885:in `with_server'
/var/lib/gems/1.8/gems/memcache-client-1.7.8/lib/memcache.rb:362:in`set'
/var/lib/gems/1.8/gems/starling-0.10.1/lib/starling.rb:69:in `set'
starling_test.rb:17
</pre></code>

It looks like starling is reading the entire queue log file before the very first operation on it. It takes a long time to respond to the first few calls and memcache-client that performs non-blocking IO throws the above errors.

I checked the time taken by starling to respond to the first fetch and set operations and on my hardware it took it more than 20 seconds for each of them.

I would appreciate any pointers and suggestions to fix this issue.

**Comment by mcastilho** [comment]
Have you fixed this issue ?

**Comment by danielribeiro** [comment]
This still happens. Guess Adam from Heroku was right: http://adam.heroku.com/past/2010/4/24/beanstalk_a_simple_and_fast_queueing_backend/

**Comment by tomlea** [comment]
This fixed this issue for us: reevoo/starling@23596e20f60bd2bd9fb4d5e9eed7b96cf61ee942

It just initialises the queues at startup.
